[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.3",
    "noisereduce>=3.0.3",
    "numpy>=2.5.3",
    "pydantic>=2.13.5",
    "python-multipart>=0.0.32",
    "scipy>=1.18.1",
    "soundfile>=0.14.0",
    "uvicorn[standard]>=0.54.0",
]
